WordVision.ec.Web/Areas/Soporte/Models/ComunicacionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WordVision.ec.Web.Areas.Soporte.Models
{
    public class ComunicacionViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Tipo de Solucitud")]
        [Required(ErrorMessage = "Tipo de Solucitud requerida.")]
        public int TipoSolicitud { get; set; }
        //public DateTime? FechaSolicitud { get; set; }
        [RegularExpression(@"^-?(?:\d+|\d{1,3}(?:.\d{3})+)?(?:\,\d+)?$", ErrorMessage = "Ingrese un valor decimal")]
        [Required(ErrorMessage = "Presupuesto requerido.")]
        public string Presupuesto { get; set; }

        [Display(Name = "Disponibilidad presupuestaria")]
        public byte[] DisponibilidadPresupuestaria { get; set; }
        [Display(Name = "Autorizacion del lider")]
        public byte[] AutorizaciondelLider { get; set; }
        //public string Informativo { get; set; }

        //public int Responsable { get; set; }

        //public int NumdeTicketTI { get; set; }
        [Display(Name = "Nombre del evento")]
        [Required(ErrorMessage = "Nombre del evento requerido.")]
        public string NombreEvento { get; set; }
        [Display(Name = "Fecha del evento")]
        [Required(ErrorMessage = "Fecha del evento requerido.")]
        public DateTime FechaEvento { get; set; }
        [Display(Name = "Hora del evento")]
        [Required(ErrorMessage = "Hora requerida.")]
        public string HoraEvento { get; set; }
        [Display(Name = "Lugar del evento")]
        [Required(ErrorMessage = "Lugar del evento requerida.")]
        public string LugarEvento { get; set; }
        [Display(Name = "Objetivo del evento")]
        [Required(ErrorMessage = "Objetivo del evento requerida.")]
        public string ObjetivoEvento { get; set; }
        [Display(Name = "Público objetivo")]
        [Required(ErrorMessage = "Público objetivo requerida.")]
        public string PublicoObjetivo { get; set; }
        [Display(Name = "Num. participantes")]
        [Required(ErrorMessage = "Num. participantes requerida.")]
        public int? NumeroParticipantes { get; set; }
        [Required(ErrorMessage = "Num. participantes requerida.")]
        public int? NumeroParticipantesP { get; set; }

        [Display(Name = "Transmisión virtual")]
        public int TransmisionVirtual { get; set; }
        [Display(Name = "Guión evento")]
        public byte[] GuionEvento { get; set; }
        [Display(Name = "Logos socios")]
        public string LogosSocios { get; set; }
        [Display(Name = "Autoridades asitirán")]
        public string PersonasAsistiran { get; set; }
        [Display(Name = "Personal WV involucrado")]
        public string PersonalWV { get; set; }
        [Display(Name = "Situaciones de interés para WV")]
        public string SituacionesInteresWV { get; set; }
        [Display(Name = "Socios a interactuar")]
        public string SociosInteractuar { get; set; }
        //public DateTime? FechaRequiereProducto { get; set; }
        //public string DescripciónProducto { get; set; }
        //public string ObjetivoProducto { get; set; }
        //public string PublicoObjetivo { get; set; }
        [Display(Name = "Mensaje clave")]
        public string MensajeClave { get; set; }
        [Display(Name = "Documento base de trabajo")]
        public byte[] DocumentoBase { get; set; }

        public int IdSolicitud { get; set; }
        public virtual SolicitudViewModel Solicitudes { get; set; }
        public ICollection<PonenteViewModel> Ponentes { get; set; }
        public ICollection<LogoSocioViewModel> LogoSocios { get; set; }
    }
}

WordVision.ec.Web/Areas/Soporte/Controllers/ComunicacionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MimeKit;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WordVision.ec.Application.Features.Maestro.Catalogos.Queries.GetById;
using WordVision.ec.Application.Features.Planificacion.MetaTacticas.Commands.Delete;
using WordVision.ec.Application.Features.Registro.Colaboradores.Queries.GetById;
using WordVision.ec.Application.Features.Soporte.Ponentes.Queries.GetAll;
using WordVision.ec.Application.Features.Soporte.Solicitudes.Commands.Create;
using WordVision.ec.Application.Features.Soporte.Solicitudes.Commands.Update;
using WordVision.ec.Application.Features.Soporte.Solicitudes.Queries.GetById;
using WordVision.ec.Web.Abstractions;
using WordVision.ec.Web.Areas.Registro.Models;
using WordVision.ec.Web.Areas.Soporte.Models;

namespace WordVision.ec.Web.Areas.Soporte.Controllers
{
    [Area("Soporte")]
    [Authorize]
    public class ComunicacionController : BaseController<ComunicacionController>
    {
        public IActionResult Index(int id = 0)
        {
            var model = new SolicitudViewModel();
            model.IdAsignadoA = id;
            return View(model);
        }


        public async Task<IActionResult> LoadAll(int idSolicitante, int op = 0)
        {
            ViewBag.Op = op;
            switch (op)
            {
                case 1:
                    var response = await _mediator.Send(new GetSolicitudByIdSolicitanteQuery() { Id = idSolicitante, Tipo = 2 });
                    if (response.Succeeded)
                    {
                        var viewModel = _mapper.Map<List<SolicitudViewModel>>(response.Data);
                        return PartialView("_ViewAll", viewModel);
                    }
                    break;

                case 2:
                    response = await _mediator.Send(new GetSolicitudByIdEstadoQuery() { Id = 1, Tipo = 2 });
                    if (response.Succeeded)
                    {
                        var viewModel = _mapper.Map<List<SolicitudViewModel>>(response.Data);
                        //var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 19 });
                        //TempData["EstadoList"] = new SelectList(cat2.Data, "Secuencia", "Nombre");

                        return PartialView("_ViewAll", viewModel);
                    }
                    break;

                case 3:
                    response = await _mediator.Send(new GetSolicitudByIdAsignadoQuery() { Id = idSolicitante });
                    if (response.Succeeded)
                    {
                        var viewModel = _mapper.Map<List<SolicitudViewModel>>(response.Data);
                        //var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 19 });
                        //TempData["EstadoList"] = new SelectList(cat2.Data, "Secuencia", "Nombre");

                        return PartialView("_ViewAll", viewModel);
                    }
                    break;
            }


            return null;
        }
        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0, int op = 0)
        {

            if (id == 0)
            {
                var entidadViewModel = new SolicitudViewModel();
                entidadViewModel.Estado = 1;
                entidadViewModel.Op = op;
                entidadViewModel.CreatedOn = DateTime.Now;
               
                var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 19 });
                entidadViewModel.EstadoList = new SelectList(cat2.Data, "Secuencia", "Nombre");
                cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 38 });
                entidadViewModel.TiposTramitesList = new SelectList(cat2.Data, "Secuencia", "Nombre");
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", entidadViewModel) });
            }
            else
            {
                var response = await _mediator.Send(new GetSolicitudByIdQuery() { Id = id });
                if (response.Succeeded)
                {
                    var entidadViewModel = _mapper.Map<SolicitudViewModel>(response.Data);
                    entidadViewModel.Op = op;
                    switch (op)
                    {
                        //case 1:
                        //    if (entidadViewModel.Estado==null)
                        //        entidadViewModel.Estado = 1;
                        //    break;
                        //case 2:
                        //    entidadViewModel.Estado = 2;


                        //    break;
                        case 3:
                            entidadViewModel.Estado = 3;
                            break;
                    }

                    var colaborador = await _mediator.Send(new GetColaboradorByIdAreaQuery() { Id = 6 });
                    if (colaborador.Succeeded)
                    {
                        var responsable = _mapper.Map<List<ColaboradorViewModel>>(colaborador.Data);
                        entidadViewModel.AsignadoAList = new SelectList(responsable, "Id", "Nombres");
                    }
                    var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 19 });
                    entidadViewModel.EstadoList = new SelectList(cat2.Data, "Secuencia", "Nombre");

                    cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 38 });
                    entidadViewModel.TiposTramitesList = new SelectList(cat2.Data, "Secuencia", "Nombre");

                    return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", entidadViewModel) });
                }
                return null;
            }
        }

        [HttpPost]  
        public async Task<JsonResult> OnPostCreateOrEdit(int id, SolicitudViewModel entidad)
        {
            try
            {
                var op = entidad.Op;
                if (ModelState.IsValid)
                {

                    if (Request.Form.Files.Count > 0)
                    {
                        for (int i = 0; i <= Request.Form.Files.Count - 1; i++)
                        {
                            IFormFile file = Request.Form.Files[i];
                            var image = file.OpenReadStream();

                            switch (Request.Form.Files[i].Name)
                            {

                                case "Comunicaciones.DisponibilidadPresupuestaria":
                                    MemoryStream ms = new();
                                    image.CopyTo(ms);
                                    entidad.Comunicaciones.DisponibilidadPresupuestaria = ms.ToArray();
                                    break;
                                case "Comunicaciones.DocumentoBase":
                                    MemoryStream msd = new();
                                    image.CopyTo(msd);
                                    entidad.Comunicaciones.DocumentoBase = msd.ToArray();
                                    break;
                                case "Comunicaciones.GuionEvento":
                                    MemoryStream msg = new();
                                    image.CopyTo(msg);
                                    entidad.Comunicaciones.GuionEvento = msg.ToArray();
                                    break;

                            }
                        }



                    }

                    if (id == 0)
                    {
                        entidad.Estado = 1;
                        entidad.TipoSistema = 2;
                        var createEntidadCommand = _mapper.Map<CreateSolicitudCommand>(entidad);
                        var result = await _mediator.Send(createEntidadCommand);
                        if (result.Succeeded)
                        {
                            id = result.Data;
                            _notify.Success($"Solicitud con ID {result.Data} Creado.");
                        }
                        else _notify.Error(result.Message);
                    }
                    else
                    {
                        entidad.Estado = entidad.Fin == 0 ? entidad.Op : entidad.Fin;
                        var updateEntidadCommand = _mapper.Map<UpdateSolicitudCommand>(entidad);
                        var result = await _mediator.Send(updateEntidadCommand);
                        if (result.Succeeded) _notify.Information($"Solicitud con ID {result.Data} Actualizado.");
                    }


                    ViewBag.Op = op;
                    switch (op)
                    {
                        case 1:
                            var response1 = await _mediator.Send(new GetSolicitudByIdSolicitanteQuery() { Id = entidad.IdColaborador, Tipo = 2 });
                            if (response1.Succeeded)
                            {
                                var viewModel = _mapper.Map<List<SolicitudViewModel>>(response1.Data);
                                //  var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 19 });
                                // ViewBag.EstadoList = new SelectList(cat2.Data, "Secuencia", "Nombre");
                                // TempData["EstadoList"] = new SelectList(cat2.Data, "Secuencia", "Nombre");

                                var html1 = await _viewRenderer.RenderViewToStringAsync("_ViewAll", viewModel);
                                html1 = html1.Replace("&op=", "&op=1");
                                //await EnviarMail(id);

                                return new JsonResult(new { isValid = true, html = html1 });
                            }

WordVision.ec.Web/Areas/Soporte/Views/Comunicacion/Index.cshtml
@using WordVision.ec.Infrastructure.Data.Identity.Models;
@using WordVision.ec.Web.Areas.Soporte.Models
@model SolicitudViewModel
@inject UserManager<ApplicationUser> UserManager

    <div class="card">
        @if (@Model.IdAsignadoA == 1)
        {
        <div class="col-sm-12 header-button">

            <button type="button" class="btn btn-primary" id="btnViewModel" onclick="jQueryModalGet('/Soporte/Comunicacion/OnGetCreateOrEdit?id=0&op=1','Solicitud de Comunicación-@UserManager.GetUserAsync(User).Result.FirstName @UserManager.GetUserAsync(User).Result.LastName @User.Claims.FirstOrDefault(x => x.Type == "Area")?.Value')">
                <i class="fa fa-plus-square"></i>
                Agregar Nuevo Requerimiento
            </button>

        </div>
        }
        <div id="viewAll" class="card-body table-responsive">
        </div>
    </div>


    @section Scripts
{
        <script src="~/js/site.js"></script>
        <script>
            $(document).ready(function () {
                loadData();
            });
            function loadData() {
                /**/
                $('#viewAll').load('/Soporte/Comunicacion/LoadAll?idSolicitante=@Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "Id")?.Value)&op=@Model.IdAsignadoA');
            /**/
        }</script>
    }

WordVision.ec.Web/Areas/Soporte/Views/Comunicacion/_CreateOrEditPonente.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@using WordVision.ec.Web.Areas.Soporte.Models
@using WordVision.ec.Infrastructure.Data.Identity.Models;
@model PonenteViewModel




<form id="create-form" method="post" asp-controller="Comunicacion" asp-action="OnPostCreateOrEditPonente" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this);" enctype="multipart/form-data">

   
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-md-6">
                    <label class="col-md-12 col-form-label texto-pregunta" asp-for="NombreApellido"></label>
                    <input asp-for="NombreApellido" type="text" name="FechaConversion" class="datepicker form-control" />
                    <span asp-validation-for="NombreApellido" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label class="col-md-12 col-form-label texto-pregunta" asp-for="Cargo"></label>
                    <input asp-for="Cargo" type="text" name="Cargo" class=" form-control" />
                    <span asp-validation-for="Cargo" class="text-danger"></span>
                </div>

            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-md-12">
                    <label class="col-md-12 col-form-label texto-pregunta" asp-for="Perfil"></label>
                    <textarea asp-for="Perfil"  name="Perfil" class=" form-control" ></textarea>
                    <span asp-validation-for="Perfil" class="text-danger"></span>
                </div>



            </div>

        </div>
    </div>
   
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-md-12">
                    <label class="col-md-12 col-form-label texto-pregunta" asp-for="Tema"></label>
                    <textarea asp-for="Tema"  name="Tema" class=" form-control" ></textarea>
                    <span asp-validation-for="Tema" class="text-danger"></span>
                </div>



            </div>

        </div>
    </div>
    <br />
    <div class="form-group justify-content-between" style="margin-bottom: 0px !important">
        
       <button type="submit" class="btn btn-success">Guardar</button>
     
        <button type="submit" class="btn btn-default close-button" data-dismiss="modal">Cancelar</button>
    </div>
</form>

WordVision.ec.Web/Areas/Soporte/Views/Comunicacion/_PonentesAll.cshtml
@using WordVision.ec.Web.Areas.Soporte.Models
@using WordVision.ec.Infrastructure.Data.Identity.Models;
@model List<PonenteViewModel>
@*<div class="col-sm-12 header-button">

            <button type="button" class="btn btn-primary" id="btnViewModel" onclick="jQueryModalGetHijo('2','/Soporte/Comunicacion/OnGetCreateOrEditPonente?id=0&idComunicacion=','Ponentes')">
                <i class="fa fa-plus-square"></i>
                Agregar
            </button>

</div>*@

<table id="ponenteTable" class="table table-striped " width="100%" cellspacing="0">
    <thead>
        <tr>

            <th>Ponente</th>
            <th data-priority="1">Cargo</th>
            <th data-priority="1">Perfíl</th>
            <th data-priority="1">Tema</th>
            <th data-priority="2" class="acciones-th">Acciones</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var solicitud in Model)
        {
        <tr>
            <td>
                @solicitud.Id
            </td>
            <td>
                @solicitud.NombreApellido  
            </td>
            <td>
                @solicitud.Cargo 
            </td>
            <td>

                @solicitud.Perfil
            </td>
            <td>

                @solicitud.Tema
            </td>
           

            <td class="acciones-td">
                <button type="button" class="btn btn-success  btn-xp" data-toggle="tooltip" data-placement="top" title="Editar" btn-xp" id="btnViewModel" onclick="jQueryModalGet('/Soporte/Comunicacion/OnGetCreateOrEditPonente?id=@solicitud.Id&idComunicacion=@solicitud.IdComunicacion','Ponentes')">
                    <i class="fas fa-eye"></i>
                </button>

                <form id="form_delete_@solicitud.Id" asp-area="Planificacion" asp-controller="ObjetivoEstrategico" method="post" asp-action="OnPostDeletePonente" asp-route-id="@solicitud.Id"  onsubmit="return jQueryModalDelete(this)">
                    <a href="javascript:$('#form_delete_@solicitud.Id').submit();" class="btn btn-danger btn-xp"><i class="fas fa-trash-alt"></i> </a>
                </form>

            </td>




        </tr>
        }
    </tbody>
</table>

<script>

    $(document).ready(function () {
        var table = $("#ponenteTable").DataTable({
            aoColumnDefs: [
                { "aTargets": [0], "bSortable": true },
                { "aTargets": [2], "asSorting": ["asc"], "bSortable": true },
            ],
            "language": {
                "url": "/lib/datatables/language/Spanish.json"
            },
            //dom: 'Bfrtip',
            //buttons: [
            //    'copyHtml5',
            //    'excelHtml5',
            //    'csvHtml5',
            //    'pdfHtml5'
            //],
            responsive: true,
            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: -1 }
            ],
            "info": false
            //columnDefs: [
            //    { responsivePriority: 1, targets: 0 },
            //    { responsivePriority: 10001, targets: 4 },
            //    { responsivePriority: 2, targets: -2 }
            //]
        });

        //var column = table.column(0);
        //// Toggle the visibility
        //column.visible(false);



        $('#solicitudTable tbody').on('dblclick', 'tr', function () {
            var data = table.row(this).data();

            jQueryModalGet('/Soporte/Comunicacion/OnGetCreateOrEditPonente?id=' + data[0], 'Ponentes');


        });

        /*  $(".dynmic-hidden-col").hide();*/

    });
</script>

WordVision.ec.Web/Areas/Soporte/Views/Comunicacion/_ViewAll.cshtml
@using WordVision.ec.Web.Areas.Soporte.Models
@using WordVision.ec.Infrastructure.Data.Identity.Models;
@model List<SolicitudViewModel>
@inject UserManager<ApplicationUser> UserManager
<table id="solicitudTable" class="table table-striped " width="100%" cellspacing="0">
    <thead>
        <tr>

            <th>N° de Solicitud</th>
            <th data-priority="1">Solicitado por</th>
            <th data-priority="1">Area</th>
            <th data-priority="1">Fecha Solicitud</th>
            <th data-priority="1">Asignado A</th>
            <th data-priority="1">Estado</th>
            <th data-priority="1">Tipo Requerimiento</th>
            <th data-priority="1">Evento/Producto</th>
            <th data-priority="1">Fecha Evento/Producto</th>

            <th data-priority="2" class="acciones-th">Acciones</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var solicitud in Model)
        {
        <tr>
            <td>
                @solicitud.Id
            </td>
            <td>
                @solicitud.Colaboradores.PrimerNombre @solicitud.Colaboradores.Apellidos 
            </td>
            <td>
                @switch (solicitud.Colaboradores.Area)
                                {
                                    case 1:<span >Proteccion Y Desarrollo</span> break;
 case 2:<span >Patrocinio</span> break;
 case 3:<span >Pa Colta</span> break;
 case 4:<span >Pa Pillaro</span> break;
 case 5:<span >Pa Tiquizambi Tixan</span> break;
 case 6:<span >Comunicaciones</span> break;
 case 7:<span >Hea Y Seguridad Corporativa</span> break;
 case 8:<span >Administracion Y Finanzas</span> break;
 case 9:<span >Finanzas</span> break;
 case 10:<span >Planeacion Y Presupuesto</span> break;
 case 11:<span >Tecnologias De La Informacion</span> break;
 case 12:<span >Gente Y Cultura</span> break;
 case 13:<span >Cadena De Abastecimiento</span> break;
 case 14:<span >Diseno, Monitoreo Y Evaluacion</span> break;
 case 15:<span >Pa Riobamba</span> break;
 case 16:<span >La Violeta</span> break;
 case 17:<span >Administracion</span> break;
 case 18:<span >Pa Chillanes</span> break;
 case 19:<span >Pa Guano</span> break;
 case 20:<span >Pa Pungala</span> break;
 case 21:<span >Pa Quito Sur</span> break;
 case 22:<span >Contabilidad</span> break;
 case 23:<span >Region Costa</span> break;
 case 24:<span >Region Sierra</span> break;
 case 25:<span >Direccion Nacional</span> break;
 case 26:<span >Marketing, Fundraising Y Comunicación</span> break;
 case 27:<span >Proyecto Youth Ready</span> break;
 case 28:<span >Pa Portoviejo</span> break;
 case 29:<span >Pa Rio Verde</span> break;
 case 30:<span >Pa Santa Ana</span> break;
 case 31:<span >Pa Baba</span> break;
 case 32:<span >Pa Flavio Alfaro</span> break;
 case 33:<span >Pa Guayaquil</span> break;
 case 34:<span >Pa Vinces</span> break;
 case 35:<span >Gam (Grant Adquisition Management)</span> break;
 case 36:<span >Cristianos Por La Niñez</span> break;
 case 37:<span >Marketing Y Fundraising</span> break;
 case 38:<span >Relaciones Eclesiales</span> break;
 case 39:<span >Participacion Comunitaria Y Patrocinio</span> break;
 case 40:<span >Acnur</span> break;
 case 41:<span >Auditoria</span> break;
 case 42:<span >Calidad Del Ministerio</span> break;
 case 43:<span >Proyecto Especial Alpacas</span> break;
 case 44:<span >Proyecto Jovenes</span> break;

                                  
                                }
            </td>
            <td>

                @solicitud.CreatedOn.ToShortDateString()
            </td>
            <td>

                @solicitud.AsignadoA
            </td>
            <td>

                @switch (solicitud.Estado)
                {
                    case 1:<span class="badge badge-primary">Nuevo</span> break;
                    case 2:<span class="badge badge-warning">Asignada</span> break;
                    case 3:<span class="badge badge-warning">En proceso</span> break;
                    case 4:<span class="badge badge-info">Finalizado</span>break;
                    case 5:<span class="badge badge-success">Cerrado</span>break;
                }
            </td>
            <td>
                    @{
                        if (solicitud.Comunicaciones != null)
                        {
                             @switch (solicitud.Comunicaciones.TipoSolicitud)
                                {
                                    case 1:<span >Evento virtual</span> break;
                                    case 2:<span >Evento presencial</span> break;
                                    case 3:<span >Cobertura de evento</span> break;
                                    case 4:<span >Producto comunicacional</span>break;
                                  
                                }
                        }
                     
                       
                      }
                </td>
            <td>
            
                    @{
                        if (solicitud.Comunicaciones != null)
                           @solicitud.Comunicaciones.NombreEvento
                       
                      }
                
            </td>
            <td>
            @{
                        if (solicitud.Comunicaciones != null)
                           @solicitud.Comunicaciones.FechaEvento.ToShortDateString()
                       
                      }
                
            </td>

            <td class="acciones-td">
            <form id="form_delete_@solicitud.Id" asp-controller="Comunicacion" method="post" asp-action="OnPostDelete" asp-route-id="@solicitud.Id" asp-route-idColaborador="@solicitud.IdColaborador" onsubmit="return jQueryModalDelete(this)" class="d-inline">
                                <a href="javascript:$('#form_delete_@solicitud.Id').submit();" class="btn btn-danger btn-xp"><i class="fas fa-trash-alt"></i> </a>
                            </form>
                <button type="button" class="btn btn-success  btn-xp" data-toggle="tooltip" data-placement="top" title="Editar" btn-xp" id="btnViewModel" onclick="jQueryModalGet('/Soporte/Comunicacion/OnGetCreateOrEdit?id=@solicitud.Id&op=@ViewBag.Op','Solicitud de Comunicación- @UserManager.GetUserAsync(User).Result.FirstName @UserManager.GetUserAsync(User).Result.LastName @User.Claims.FirstOrDefault(x => x.Type == "Area")?.Value')">
                    <i class="fas fa-eye"></i>
                </button>

                @*<button type="button" class="btn btn-primary  btn-xp" title="Agregar" id="btnViewModel" onclick="jQueryModalGet('/Planificacion/IndicadorPOA/OnGetCreateOrEdit?id=0&idProducto=@producto.Id&idGestion=@Model.IdGestion&idIndicadorEstrategia=@Model.Id','Indicador de Producto')">
                <i class="fas fa-plus-square"></i>
            </button>*@
            </td>





        </tr>
        }
    </tbody>
</table>

<script>

    $(document).ready(function () {
        var table = $("#solicitudTable").DataTable({
            aoColumnDefs: [
                { "aTargets": [0], "bSortable": true },
                { "aTargets": [2], "asSorting": ["asc"], "bSortable": true },
            ],
            "language": {
                "url": "/lib/datatables/language/Spanish.json"
            },
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ],
            responsive: true,
            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: -1 }
            ],
            "info": false
            //columnDefs: [
            //    { responsivePriority: 1, targets: 0 },
            //    { responsivePriority: 10001, targets: 4 },
            //    { responsivePriority: 2, targets: -2 }
            //]
        });

        //var column = table.column(0);
        //// Toggle the visibility
        //column.visible(false);



        $('#solicitudTable tbody').on('dblclick', 'tr', function () {
            var data = table.row(this).data();

            jQueryModalGet('/Soporte/Comunicacion/OnGetCreateOrEdit?id=' + data[0], 'Solicitud');


        });

        /*  $(".dynmic-hidden-col").hide();*/

    });
</script>