WordVision.ec.Web/Areas/Planificacion/Models/ObjetivoEstrategicoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using WordVision.ec.Domain.Entities.Planificacion;

namespace WordVision.ec.Web.Areas.Planificacion.Models
{
    public class ObjetivoEstrategicoViewModel
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Programa { get; set; }
        public string Cwbo { get; set; }
        public int Categoria { get; set; }
        public int AreaPrioridad { get; set; }
        public int? Dimension { get; set; }

        public int CargoResponsable { get; set; }

        public int IdEstrategia { get; set; }

        //CAMPOS PERSONALIZADOS
        public SelectList DimensionList { get; set; }
        public SelectList AreaList { get; set; }
        public SelectList ProgramaList { get; set; }
        public SelectList CwboList { get; set; }
        public SelectList AnioFiscalList { get; set; }
        public virtual List<FactorCriticoExito> FactorCriticoExitos { get; set; }
        public ICollection<ProductoObjetivo> ProductoObjetivos { get; set; }
    }
}

WordVision.ec.Web/Areas/Planificacion/Controllers/ObjetivoEstrategicoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WordVision.ec.Application.Features.Maestro.Catalogos.Queries.GetById;
using WordVision.ec.Application.Features.Planificacion.EstrategiaNacionales.Queries.GetById;
using WordVision.ec.Application.Features.Planificacion.ObjetivoEstrategicoes.Commands.Create;
using WordVision.ec.Application.Features.Planificacion.ObjetivoEstrategicoes.Commands.Delete;
using WordVision.ec.Application.Features.Planificacion.ObjetivoEstrategicoes.Commands.Update;
using WordVision.ec.Application.Features.Planificacion.ObjetivoEstrategicoes.Queries.GetAllCached;
using WordVision.ec.Application.Features.Planificacion.ObjetivoEstrategicoes.Queries.GetById;
using WordVision.ec.Application.Features.Registro.Colaboradores.Queries.GetById;
using WordVision.ec.Web.Abstractions;
using WordVision.ec.Web.Areas.Planificacion.Models;

namespace WordVision.ec.Web.Areas.Planificacion.Controllers
{
    [Area("Planificacion")]
    [Authorize]
    public class ObjetivoEstrategicoController : BaseController<ObjetivoEstrategicoController>
    {

        public IActionResult Index()
        {
            var model = new ObjetivoEstrategicoViewModel();

            return View(model);
        }

        public async Task<IActionResult> LoadAll()
        {
            var response = await _mediator.Send(new GetAllObjetivoEstrategicoesCachedQuery());
            if (response.Succeeded)
            {
                var viewModel = _mapper.Map<List<ObjetivoEstrategicoViewModel>>(response.Data);

                return PartialView("_ViewAll", viewModel);
            }
            return null;
        }

        public async Task<IActionResult> LoadObjetivo(int idEstrategia, int idCategoria, string AnioGestion, string esCoordinadorEstrategico)
        {
            int idColaborador = 0;
            if (esCoordinadorEstrategico == "N")
            {
                switch (Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "Nivel")?.Value))
                {
                    case 2:
                        idColaborador = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "Id")?.Value);
                        break;
                    case 3:
                        idColaborador = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "ReportaA")?.Value);
                        break;
                    case 4:
                        idColaborador = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "ReportaA")?.Value);
                        var responseGerencia = await _mediator.Send(new GetColaboradorByIdQuery() { Id = idColaborador });
                        if (responseGerencia.Succeeded)
                        {
                            var responseNivel = await _mediator.Send(new GetColaboradorByNivelQuery() { Nivel1 = 1, Nivel2 = 2 });

                            idColaborador = responseNivel.Data.Where(c => c.Cargo == responseGerencia.Data.Estructuras.ReportaID).FirstOrDefault().Id;
                        }
                        break;
                }


            }
            var response = await _mediator.Send(new GetEstrategiaNacionalByIdQuery() { Id = idEstrategia, IdColaborador = idColaborador, Nivel = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "Nivel")?.Value) });
            if (response.Succeeded)
            {

                var entidadViewModel = _mapper.Map<EstrategiaNacionalViewModel>(response.Data);
                entidadViewModel.CategoriaObjetivo = idCategoria;
                entidadViewModel.AnioGestion = AnioGestion;
                entidadViewModel.EsCoordinadorEstrategico = esCoordinadorEstrategico;
                ViewBag.Ciclo = entidadViewModel.Nombre;
                var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 4 });
                entidadViewModel.AreaPrioridadList = new SelectList(cat2.Data, "Secuencia", "Nombre");
                return PartialView(idCategoria == 2 ? "_ViewAll" : "_ViewAllNacional", entidadViewModel);
            }
            return null;
        }

        //[Breadcrumb("Objetivo", AreaName = "Planificacion", FromAction = "OnGetCreateOrEdit", FromController = typeof(EstrategiaNacionalController))]
        public async Task<JsonResult> OnGetCreateOrEdit(int id = 0, int idEstrategia = 0, int categoria = 0)
        {
            // var brandsResponse = await _mediator.Send(new GetAllBrandsCachedQuery());
            //var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 3 });
            //var DimList = new SelectList(cat2.Data, "Secuencia", "Nombre");

            var cat3 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 4 });
            var AreaList = new SelectList(cat3.Data, "Secuencia", "Nombre");

            var catPrograma = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 17 });
            var ProgramaList = new SelectList(catPrograma.Data, "Secuencia", "Nombre");

            var catCtwo = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 18 });
            var CwboList = new SelectList(catCtwo.Data, "Secuencia", "Nombre");
            if (id == 0)
            {
                var entidadViewModel = new ObjetivoEstrategicoViewModel();
                entidadViewModel.Categoria = categoria;
                entidadViewModel.IdEstrategia = idEstrategia;
                //entidadViewModel.DimensionList = DimList;
                entidadViewModel.AreaList = AreaList;
                entidadViewModel.ProgramaList = ProgramaList;
                entidadViewModel.CwboList = CwboList;
                //  return View("_CreateOrEdit", entidadViewModel);
                return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", entidadViewModel) });
            }
            else
            {
                var response = await _mediator.Send(new GetObjetivoEstrategicoByIdQuery() { Id = id });
                if (response.Succeeded)
                {
                    var entidadViewModel = _mapper.Map<ObjetivoEstrategicoViewModel>(response.Data);
                    entidadViewModel.Categoria = categoria;
                    entidadViewModel.IdEstrategia = idEstrategia;
                    //entidadViewModel.DimensionList = DimList;
                    entidadViewModel.AreaList = AreaList;
                    entidadViewModel.ProgramaList = ProgramaList;
                    entidadViewModel.CwboList = CwboList;
                    // return View("_CreateOrEdit", entidadViewModel);
                    return new JsonResult(new { isValid = true, html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", entidadViewModel) });
                }
                return null;
            }
        }

        [HttpPost]
        public async Task<JsonResult> OnPostCreateOrEdit(int id, ObjetivoEstrategicoViewModel entidad)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (id == 0)
                    {
                        var createEntidadCommand = _mapper.Map<CreateObjetivoEstrategicoCommand>(entidad);
                        var result = await _mediator.Send(createEntidadCommand);
                        if (result.Succeeded)
                        {
                            id = result.Data;
                            _notify.Success($"Objetivo con ID {result.Data} Creado.");
                        }
                        else _notify.Error(result.Message);
                    }
                    else
                    {
                        var updateEntidadCommand = _mapper.Map<UpdateObjetivoEstrategicoCommand>(entidad);
                        var result = await _mediator.Send(updateEntidadCommand);
                        if (result.Succeeded) _notify.Information($"Objetivo con ID {result.Data} Actualizado.");
                    }
                    var response = await _mediator.Send(new GetEstrategiaNacionalByIdQuery() { Id = entidad.IdEstrategia });
                    if (response.Succeeded)
                    {

                        var entidadViewModel = _mapper.Map<EstrategiaNacionalViewModel>(response.Data);
                        entidadViewModel.CategoriaObjetivo = entidad.Categoria;
                        var cat2 = await _mediator.Send(new GetListByIdDetalleQuery() { Id = 4 });
                        entidadViewModel.AreaPrioridadList = new SelectList(cat2.Data, "Secuencia", "Nombre");
                        var html1 = await _viewRenderer.RenderViewToStringAsync(entidad.Categoria == 2 ? "_ViewAll" : "_ViewAllNacional", entidadViewModel);
                        return new JsonResult(new { isValid = true, opcion = Convert.ToInt32(entidad.Categoria), page = entidad.Categoria == 2 ? "#viewAll" : "#viewAllNacional", html = html1 });
                    }
                    else
                    {
                        _notify.Error(response.Message);
                        return null;
                    }
                }
                else
                {
                    var html = await _viewRenderer.RenderViewToStringAsync("_CreateOrEdit", entidad);
                    return new JsonResult(new { isValid = false, html = html });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("OnPostCreateOrEdit", ex);
                _notify.Error("Error al insertar ObjetivoEstrategico");
            }
            return null;
        }


        public async Task<JsonResult> OnPostDelete(int id = 0, int idEstrategia = 0, int idCategoria = 0)
        {
            var deleteCommand = await _mediator.Send(new DeleteObjetivoEstrategicoCommand { Id = id });

WordVision.ec.Web/Areas/Planificacion/Views/ObjetivoEstrategico/_CreateOrEdit.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@using WordVision.ec.Web.Areas.Planificacion.Models
@model ObjetivoEstrategicoViewModel


<form id="create-form" method="post" asp-controller="ObjetivoEstrategico" asp-action="OnPostCreateOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryModalPost(this);" enctype="multipart/form-data">

    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <div class="col-md-12">
                    <label class="col-md-12 col-form-label texto-pregunta">Objetivo de Resultado</label>
                    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.ObjetivoEstrategico.Edit)).Result.Succeeded)
                    {
                        <textarea asp-for="Descripcion" name="Descripcion" class="form-control"></textarea>
                    }
                    else
                    { <textarea asp-for="Descripcion" name="Descripcion" class="form-control" readonly></textarea>}

                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                @*<div class="col-md-3">*@
                @*<label class="col-md-12 col-form-label texto-pregunta">Categoria</label>
                    <select asp-for="Categoria" name="Categoria" class="form-control">
                        <option value="N">Nacional</option>
                        <option value="B">Bloque</option>

                    </select>
                    <span asp-validation-for="Categoria" class="text-danger"></span>*@
                @Html.HiddenFor(x => x.Categoria, new { name = "Categoria" })
                @Html.HiddenFor(x => x.IdEstrategia, new { name = "IdEstrategia" })

                @*</div>*@

                @*<div class="col-md-4">
                    <label class="col-md-12 col-form-label texto-pregunta text-left">Area Prioridad</label>*@
                @*<select asp-for="AreaPrioridad" name="AreaPrioridad" class="form-control">
                        <option value="N">Area1</option>
                        <option value="B">Area2</option>

                    </select>*@
                @* @Html.DropDownListFor(x => x.AreaPrioridad, Model.AreaList, new { @class = "form-control" })*@
                @*<span asp-validation-for="AreaPrioridad" class="text-danger"></span>
                    </div>*@

                <div class="col-md-6">
                    <label class="col-md-12 col-form-label texto-pregunta">Area</label>
                    @*<select asp-for="Dimension" name="Dimension" class="form-control">
                            <option value="A">Dim1</option>
                            <option value="C">Dim2</option>
                            <option value="F">Dim3</option>

                        </select>*@
                    @Html.DropDownListFor(x => x.AreaPrioridad, Model.AreaList, new { @class = "form-control" })
                    <span asp-validation-for="AreaPrioridad" class="text-danger"></span>
                </div>
                <input type="hidden" value="1" name="CargoResponsable" />

                @*<div class="col-md-4">
                        <label class="col-md-12 col-form-label texto-pregunta">Responsable</label>
                        <select asp-for="CargoResponsable" name="CargoResponsable" class="form-control">
                            <option value="1">Responsable1</option>
                            <option value="2">Responsable2</option>
                            <option value="3">Responsable3</option>

                        </select>
                        <span asp-validation-for="CargoResponsable" class="text-danger"></span>
                    </div>*@

            </div>
            @if (Model.Categoria==1)
            {
                <div class="form-group row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label class="col-md-12 col-form-label texto-pregunta">Programa Tecnico</label>
                                @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.ObjetivoEstrategico.Edit)).Result.Succeeded)
                                    {
                                        <textarea asp-for="Programa" name="Programa" class="form-control"></textarea>
                                    }
                                    else
                                    { <textarea asp-for="Programa" name="Programa" class="form-control" readonly></textarea>}*@
                                @Html.DropDownListFor(x => x.Programa, Model.ProgramaList, new { @class = "form-control" })
                                <span asp-validation-for="Programa" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label class="col-md-12 col-form-label texto-pregunta ">CWBO</label>
                               @* @if ((AuthorizationService.AuthorizeAsync(User, Permissions.ObjetivoEstrategico.Edit)).Result.Succeeded)
                                    {
                                        <textarea asp-for="Cwbo" name="Cwbo" class="form-control"></textarea>
                                    }
                                    else {<textarea asp-for="Cwbo" name="Cwbo" class="form-control" readonly></textarea> }*@
                                @Html.DropDownListFor(x => x.Cwbo, Model.CwboList, new { @class = "form-control" })
                                <span asp-validation-for="Cwbo" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            }
            



        </div>
    </div>

   
                    <br />
                    <div class="form-group justify-content-between" style="margin-bottom: 0px !important">
                        @if ((AuthorizationService.AuthorizeAsync(User, Permissions.ObjetivoEstrategico.Create)).Result.Succeeded)
                        {<input type="hidden" value="false" name="band" id="band" />
                            <button type="submit" class="btn btn-success">Guardar</button>
                        }
                        else
                        { <input type="hidden" value="true" name="band" id="band" />}
                        <button type="submit" class="btn btn-default close-button" data-dismiss="modal">Cancelar</button>
                    </div>
</form>


        
        <script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
            $(function () {
                $('#create-form *').prop('disabled', (document.getElementById("band").value == "true"));
                $(".datepicker").datepicker({
                    format: "dd-mm-yyyy",
                    autoclose: true,
                    todayBtn: true });
        //$("#VigDesde").datepicker({ dateFormat: 'dd-mm-yy' });
        //$("#VigHasta").datepicker({ dateFormat: 'dd-mm-yy' });

    });

    $("#BrandId").select2({
        placeholder: "Select a Category",
        theme: "bootstrap4",
        escapeMarkup: function (m) {
            return m;
        }
    });


       var num = 0;
        function AgregaConcepto() {
            let Anio = document.getElementById("AnioGestion").value;
            let Descripcion = document.getElementById("DescGestion").value;
            let Estado = document.getElementById("EstadoGestion").value;
            let IdEstrategia = document.getElementById("Id").value;

            if (Anio.length == 0) {
                alert("Ingrese la Gestion.");
                return;
            }


            //agregamos tabla
            let Tabla = document.getElementById("gestionTable");
            let TR = document.createElement("tr");
            TR.setAttribute('id', num);
           // let TDId = document.createElement("td");
            let TDAnio = document.createElement("td");
            let TDDescripcion = document.createElement("td");
            let TDEstado = document.createElement("td");
            let TDEliminar = document.createElement("td");
            TDEliminar.className = "text-right";
            //let TDTotal = document.createElement("td");
           // TR.appendChild(TDId);
            TR.appendChild(TDAnio);
            TR.appendChild(TDDescripcion);
            TR.appendChild(TDEstado);
            TR.appendChild(TDEliminar);
            //TR.appendChild(TDTotal);
           // TDId.innerHTML = num;
            TDAnio.innerHTML = Anio;
            TDDescripcion.innerHTML = Descripcion;
            TDEstado.innerHTML = Estado;
            TDEliminar.innerHTML = " <button type='button' onclick='EliminaFila("+num+")' class='btn btn-danger btn-xp'><i class='fas fa-trash-alt'></i>  Eliminar</button>";
            //TDTotal.innerHTML = parseFloat(Cantidad) * parseFloat(Precio);
            Tabla.appendChild(TR);

            //agregamos hiddens
            let DivConceptos = document.getElementById("divGestion");
            let HiddenIndex = document.createElement("input");
            let HiddenAnio = document.createElement("input");
            let HiddenDescripcion = document.createElement("input");
            let HiddenEstado = document.createElement("input");
            HiddenIndex.name = "gestion.Index";
            HiddenIndex.value = num;
            HiddenIndex.type = "hidden";
            HiddenAnio.name = "gestion[" + num + "].Anio";
            HiddenAnio.value = Anio;
            HiddenAnio.type = "hidden";
            HiddenDescripcion.name = "gestion[" + num + "].Descripcion";
            HiddenDescripcion.value = Descripcion;
            HiddenDescripcion.type = "hidden";
            HiddenEstado.name = "gestion[" + num + "].Estado";
            HiddenEstado.value = Estado;
            HiddenEstado.type = "hidden";
            DivConceptos.appendChild(HiddenIndex);
            DivConceptos.appendChild(HiddenAnio);
            DivConceptos.appendChild(HiddenDescripcion);
            DivConceptos.appendChild(HiddenEstado);

            document.getElementById("AnioGestion").value = "";
            document.getElementById("DescGestion").value = "";
            document.getElementById("EstadoGestion").value = "";

            num++;



            //var GestionViewModel = {
            //    Anio: Nombre,
            //    Descripcion: Hablado,
            //    Estado: Escrito,
            //    IdEstrategia: IdEstrategia

            //};

        @*$.ajax({
            type: "post",
            url:'@Url.Action("OnPostCreateOrEdit", "Idioma", new { area = "Registro" })',
            data: GestionViewModel,
            datatype: "json",
            cache: false,
            success: function (data) {
            /* alert('Validooo');*/

            },
            error: function(xhr) {
            //    alert('No Valid Data');
            }
        });*@

        }

    function deleteRow(id) {
        $("#" + id).remove();
    }

    function EliminaFila(id) {

        $("#" + id).remove();

        var GestionViewModel = {
            id: id
        };

         @*$.ajax({
            type: "post",
            url:'@Url.Action("OnPostDelete", "Idioma", new { area = "Registro" })',
             data: GestionViewModel,
            datatype: "json",
            cache: false,
            success: function (data) {
            /*  alert('Validooo');*/

            },
            error: function(xhr) {
               // alert('No Valid Data');
            }
        });*@
    }

        </script>